[kivy]
# Kivy 配置文件

[widgets]
# 设置默认字体（适用于所有组件）
fontname = fonts/AaBianYaKai.ttf

[text]
# Text 相关组件的默认字体
font_name = fonts/AaBianYaKai.ttf

[textinput]
# TextInput 组件字体
font_name = fonts/AaBianYaKai.ttf
